@url = http://localhost:3000/api

###

POST {{url}}/auth/register
Content-Type: application/json

{
  "username": "baojie",
  "password": "123456"
}

###

POST {{url}}/auth/login
Content-Type: application/json

{
  "username": "baojie1",
  "password": "123456"
}

###
GET {{url}}/auth/profile
Authorization: Bearer 1eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVkZjliOTBjOTBmZmJkMjhjMGY3ZDRhNyIsImlhdCI6MTU3NjY0ODc0OH0.50PSAm_QGZQ5UlHFyQzsNsG3bkmDRoWVTuyuPp8sOYg

###
GET {{url}}/file/pdf

###
POST {{url}}/file/pdf
Content-Type: application/json
{
  "html": "<h1>hello</h1>"
}

###
GET {{url}}/users
